services:
  dashboard:
    image: ghcr.io/robnice/omv-service-dashboard:latest
    container_name: omv-service-dashboard
    restart: unless-stopped
    pid: "host"
    privileged: true
    devices:
      - "/dev:/dev"
    ports:
      - "8069:3000" # change outer and inner port to your needs, if you change inner port, change it in the config.json too
    environment:
      PROC_ROOT: /host/proc
      SYS_ROOT: /host/sys
      HOST_ROOT: /hostroot
      DPKG_ROOT: /host/var/lib/dpkg
    working_dir: /app
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/lib/dpkg:/host/var/lib/dpkg:ro
      - /:/hostroot:ro,rslave
      - /mnt/store1/config/omv-landingpage:/config

